const alpha = new Map([
  ['A', '  A  \n A A \nAAAAA\nA   A\nA   A'],
  ['B', 'BBBB \nB   B\nBBBB \nB   B\nBBBB '],
  ['C', ' CCC \nC   C\nC    \nC   C\n CCC '],
  ['D', 'DDD  \nD  D \nD   D\nD  D \nDDD  '],
  ['E', 'EEEEE\nE    \nEEE  \nE    \nEEEEE'],
  ['F', 'FFFFF\nF    \nFFF  \nF    \nF    '],
  ['G', ' GGG \nG    \nG  GG\nG   G\n GGG '],
  ['H', 'H   H\nH   H\nHHHHH\nH   H\nH   H'],
  ['I', 'IIIII\n  I  \n  I  \n  I  \nIIIII'],
  ['J', ' JJJ \n   J \n   J \nJ  J \n JJ  '],
  ['K', 'K  K \nK K  \nKK   \nK K  \nK  K '],
  ['L', 'L    \nL    \nL    \nL    \nLLLLL'],
  ['M', 'M   M\nMM MM\nM M M\nM   M\nM   M'],
  ['N', 'N   N\nNN  N\nN N N\nN  NN\nN   N'],
  ['O', ' OOO \nO   O\nO   O\nO   O\n OOO '],
  ['P', 'PPPP \nP   P\nPPPP \nP    \nP    '],
  ['Q', ' QQQ \nQ   Q\nQ   Q\nQ  QQ\n QQQQ'],
  ['R', 'RRRR \nR   R\nRRRR \nR R  \nR  RR'],
  ['S', ' SSS \nS    \n SSS \n    S\nSSS  '],
  ['T', 'TTTTT\n  T  \n  T  \n  T  \n  T  '],
  ['U', 'U   U\nU   U\nU   U\nU   U\n UUU '],
  ['V', 'V   V\nV   V\nV   V\n V V \n  V  '],
  ['W', 'W   W\nW   W\nW W W\nWW WW\nW   W'],
  ['X', 'X   X\n X X \n  X  \n X X \nX   X'],
  ['Y', 'Y   Y\n Y Y \n  Y  \n  Y  \n  Y  '],
  ['Z', 'ZZZZZ\n   Z \n  Z  \n Z   \nZZZZZ'],
  [' ', '      \n      \n      \n      \n      '],
]);

module.exports = { alpha };
